"""Download Composio's brand SVGs for every connector that lacks a bundled glyph,
SVGO-minify them, and write inline to src/brandSvgs.ts. The native webview can't
load remote logos, so they must be bundled (same reason BRANDS is inline).

Pipeline: fetch vector SVGs (skip raster-embedded) -> svgo --multipass -> keep
those with a viewBox and <=20KB (a handful of pathological/illustration logos are
dropped to a monogram) -> sanitize -> inline.

Requires `npx svgo` (Node). Run from repo root or finetune/.

    python fetch_brand_svgs.py
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import tempfile
import urllib.request
from pathlib import Path

HERE = Path(__file__).parent
ROOT = HERE.parent
CONNECTOR_DATA = ROOT / "src" / "connectorData.ts"
BRAND_LOGOS = ROOT / "src" / "brandLogos.tsx"
OUT = ROOT / "src" / "brandSvgs.ts"
BASE = "https://logos.composio.dev/api/"
MAX_BYTES = 20000


def sanitize(svg: str) -> str:
    svg = re.sub(r"<script\b.*?</script>", "", svg, flags=re.S | re.I)
    svg = re.sub(r"\son\w+\s*=\s*\"[^\"]*\"", "", svg, flags=re.I)
    svg = re.sub(r"\son\w+\s*=\s*'[^']*'", "", svg, flags=re.I)
    # Strip fixed width/height on the ROOT <svg> so it scales to its container
    # (viewBox preserves aspect). Only the first tag.
    m = re.search(r"<svg\b[^>]*>", svg, flags=re.I)
    if m:
        tag = re.sub(r'\s(width|height)\s*=\s*"[^"]*"', "", m.group(0), flags=re.I)
        svg = svg[: m.start()] + tag + svg[m.end():]
    return svg.strip()


def fetch(slug: str) -> str | None:
    try:
        req = urllib.request.Request(BASE + slug, headers={"User-Agent": "gf/1.0", "accept": "image/svg+xml"})
        with urllib.request.urlopen(req, timeout=15) as r:
            if "svg" not in (r.headers.get("content-type") or ""):
                return None
            s = r.read().decode("utf-8")
            return None if "base64" in s.lower() else s   # drop raster-embedded blobs
    except Exception:
        return None


def main() -> None:
    ids = re.findall(r"id: '([a-z0-9_]+)'", CONNECTOR_DATA.read_text())
    bundled = set(re.findall(r"^\s{2}([a-z0-9_]+):\s*\{\s*color:", BRAND_LOGOS.read_text(), re.M))
    todo = [i for i in dict.fromkeys(ids) if i not in bundled and i != "plaid"]
    print(f"connectors: {len(ids)} | already bundled: {len(bundled)} | fetching: {len(todo)}")

    tmp = Path(tempfile.mkdtemp(prefix="brandsvg_"))
    got = 0
    for n, cid in enumerate(todo, 1):
        s = fetch(cid)
        if s and "viewBox" in s:
            (tmp / f"{cid}.svg").write_text(s, encoding="utf-8")
            got += 1
        if n % 150 == 0:
            print(f"  {n}/{len(todo)}")
    print(f"fetched {got} vector SVGs -> svgo…")
    subprocess.run(["npx", "--yes", "svgo", "-f", str(tmp), "-o", str(tmp), "--multipass", "-q"], check=False)

    svgs: dict[str, str] = {}
    big = nobox = 0
    for f in tmp.iterdir():
        raw = f.read_text(encoding="utf-8")
        if "viewBox" not in raw:
            nobox += 1; continue
        s = sanitize(raw)
        if len(s) > MAX_BYTES:
            big += 1; continue
        svgs[f.stem] = s

    body = ",\n".join(f"  {json.dumps(k)}: {json.dumps(v)}" for k, v in sorted(svgs.items()))
    OUT.write_text(
        "// Inline brand SVGs from Composio for connectors not in BRANDS (the native\n"
        "// webview can't load remote logos). SVGO-minified, sanitized, sized to scale.\n"
        "// A few pathologically-large/raster ones are excluded (monogram fallback).\n"
        "// Generated by finetune/fetch_brand_svgs.py — do not hand-edit.\n"
        "export const BRAND_SVGS: Record<string, string> = {\n" + body + "\n};\n",
        encoding="utf-8",
    )
    # Tiny id list so hasBrand() decides logo-vs-monogram without the big payload.
    (ROOT / "src" / "brandSvgKeys.ts").write_text(
        "// Ids of connectors whose logo lives in brandSvgs.ts (lazily loaded). This\n"
        "// tiny list lets hasBrand() decide logo-vs-monogram synchronously without\n"
        "// pulling the big SVG payload. Generated by finetune/fetch_brand_svgs.py.\n"
        "export const BRAND_SVG_IDS: ReadonlySet<string> = new Set([\n"
        + ",\n".join(f"  {json.dumps(k)}" for k in sorted(svgs)) + ",\n]);\n",
        encoding="utf-8",
    )
    kb = OUT.stat().st_size / 1024
    print(f"\nwrote {len(svgs)} inline SVGs (dropped {big} >20KB + {nobox} no-viewBox) -> brandSvgs.ts ({kb:.0f} KB) + brandSvgKeys.ts")


if __name__ == "__main__":
    main()
