"""Download Composio's brand SVGs for every connector that lacks a bundled glyph,
and write them inline to src/brandSvgs.ts. The native webview can't load remote
logos, so they must be bundled — same reason BRANDS (simple-icons single-paths)
is inline. These are full multi-color SVGs, kept as sanitized markup.

Skips connectors already in BRANDS (those keep their cleaner single-path glyph)
and any toolkit Composio has no SVG for (those stay a monogram).

    python fetch_brand_svgs.py
"""
from __future__ import annotations

import json
import re
import urllib.request
from pathlib import Path

HERE = Path(__file__).parent
ROOT = HERE.parent
CONNECTOR_DATA = ROOT / "src" / "connectorData.ts"
BRAND_LOGOS = ROOT / "src" / "brandLogos.tsx"
OUT = ROOT / "src" / "brandSvgs.ts"
BASE = "https://logos.composio.dev/api/"


def sanitize(svg: str) -> str:
    # Drop anything executable — these get inlined via dangerouslySetInnerHTML.
    svg = re.sub(r"<script\b.*?</script>", "", svg, flags=re.S | re.I)
    svg = re.sub(r"<!--.*?-->", "", svg, flags=re.S)
    svg = re.sub(r"\son\w+\s*=\s*\"[^\"]*\"", "", svg, flags=re.I)
    svg = re.sub(r"\son\w+\s*=\s*'[^']*'", "", svg, flags=re.I)
    svg = re.sub(r"<foreignObject\b.*?</foreignObject>", "", svg, flags=re.S | re.I)
    # Strip fixed width/height on the ROOT <svg> so it scales to its container
    # (viewBox stays, so aspect is preserved). Only the first tag.
    m = re.search(r"<svg\b[^>]*>", svg, flags=re.I)
    if m:
        tag = re.sub(r'\s(width|height)\s*=\s*"[^"]*"', "", m.group(0), flags=re.I)
        svg = svg[: m.start()] + tag + svg[m.end():]
    # light minify
    svg = re.sub(r">\s+<", "><", svg)
    svg = re.sub(r"\s{2,}", " ", svg).strip()
    return svg


def fetch(slug: str) -> str | None:
    try:
        req = urllib.request.Request(BASE + slug, headers={"User-Agent": "gf/1.0", "accept": "image/svg+xml"})
        with urllib.request.urlopen(req, timeout=15) as r:
            if "svg" not in (r.headers.get("content-type") or ""):
                return None
            return sanitize(r.read().decode("utf-8"))
    except Exception:
        return None


def main() -> None:
    ids = re.findall(r"id: '([a-z0-9_]+)'", CONNECTOR_DATA.read_text())
    bundled = set(re.findall(r"^\s{2}([a-z0-9_]+):\s*\{\s*color:", BRAND_LOGOS.read_text(), re.M))
    todo = [i for i in dict.fromkeys(ids) if i not in bundled and i != "plaid"]
    print(f"connectors: {len(ids)} | already bundled: {len(bundled)} | fetching SVGs for: {len(todo)}")

    svgs: dict[str, str] = {}
    got = miss = 0
    for n, cid in enumerate(todo, 1):
        s = fetch(cid)
        # Cap at 8KB and skip raster-embedded SVGs — bigger ones bloat the bundle
        # and look bad shrunk to 24px; they fall back to a monogram.
        if s and len(s) <= 8000 and "base64" not in s.lower():
            svgs[cid] = s; got += 1
        else:
            miss += 1
        if n % 100 == 0:
            print(f"  {n}/{len(todo)} ({got} found)")

    body = ",\n".join(f"  {json.dumps(k)}: {json.dumps(v)}" for k, v in sorted(svgs.items()))
    OUT.write_text(
        "// Inline brand SVGs from Composio for connectors not in BRANDS (the native\n"
        "// webview can't load remote logos). Sanitized + sized to scale. Generated by\n"
        "// finetune/fetch_brand_svgs.py — do not hand-edit.\n"
        "export const BRAND_SVGS: Record<string, string> = {\n" + body + "\n};\n",
        encoding="utf-8",
    )
    kb = OUT.stat().st_size / 1024
    print(f"\nwrote {got} SVGs ({miss} had none) -> src/brandSvgs.ts ({kb:.0f} KB)")


if __name__ == "__main__":
    main()
