"""
Dedicated DOCX templates for specific document types.
Each template takes structured JSON data (same as PDF templates) and renders a professional Word document.
"""

import io
import logging
from datetime import datetime
from docx import Document
from docx.shared import Inches, Pt, Cm, RGBColor, Emu
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn

logger = logging.getLogger(__name__)

# Brand colors
PRIMARY = RGBColor(236, 72, 153)
DARK = RGBColor(26, 26, 26)
MID = RGBColor(85, 85, 85)
LIGHT = RGBColor(136, 136, 136)
WHITE = RGBColor(255, 255, 255)
ACCENT_BLUE = RGBColor(37, 99, 235)
ACCENT_GREEN = RGBColor(22, 163, 106)
LIGHT_BG = RGBColor(248, 248, 248)
TABLE_HEADER_BG = RGBColor(26, 26, 26)
ALT_ROW_BG = RGBColor(245, 245, 245)


def _rgb_hex(color: RGBColor) -> str:
    return str(color)


def _set_cell_shading(cell, color: RGBColor):
    shading = cell._element.get_or_add_tcPr()
    shd = shading.makeelement(qn('w:shd'), {
        qn('w:val'): 'clear',
        qn('w:color'): 'auto',
        qn('w:fill'): _rgb_hex(color),
    })
    shading.append(shd)


def _set_cell_borders(cell, top=None, bottom=None, left=None, right=None):
    tc_pr = cell._element.get_or_add_tcPr()
    borders = tc_pr.makeelement(qn('w:tcBorders'), {})
    for edge, val in [('top', top), ('bottom', bottom), ('left', left), ('right', right)]:
        if val:
            border = borders.makeelement(qn(f'w:{edge}'), {
                qn('w:val'): val.get('val', 'single'),
                qn('w:sz'): str(val.get('sz', 4)),
                qn('w:color'): val.get('color', '000000'),
                qn('w:space'): '0',
            })
            borders.append(border)
    tc_pr.append(borders)


def _add_horizontal_rule(doc, color='e0e0e0', size=4):
    p = doc.add_paragraph()
    p.paragraph_format.space_before = Pt(2)
    p.paragraph_format.space_after = Pt(2)
    pPr = p._element.get_or_add_pPr()
    pBdr = pPr.makeelement(qn('w:pBdr'), {})
    bottom = pBdr.makeelement(qn('w:bottom'), {
        qn('w:val'): 'single',
        qn('w:sz'): str(size),
        qn('w:color'): color,
        qn('w:space'): '1',
    })
    pBdr.append(bottom)
    pPr.append(pBdr)
    return p


def _styled_table(doc, headers, rows, col_widths=None):
    table = doc.add_table(rows=1 + len(rows), cols=len(headers))
    table.alignment = WD_TABLE_ALIGNMENT.CENTER

    for i, h in enumerate(headers):
        cell = table.rows[0].cells[i]
        cell.text = ''
        p = cell.paragraphs[0]
        run = p.add_run(str(h))
        run.font.size = Pt(9)
        run.font.color.rgb = WHITE
        run.font.bold = True
        run.font.name = 'Calibri'
        p.paragraph_format.space_before = Pt(4)
        p.paragraph_format.space_after = Pt(4)
        _set_cell_shading(cell, TABLE_HEADER_BG)

    for r_idx, row_data in enumerate(rows):
        for c_idx, val in enumerate(row_data):
            cell = table.rows[r_idx + 1].cells[c_idx]
            cell.text = ''
            p = cell.paragraphs[0]
            run = p.add_run(str(val))
            run.font.size = Pt(9)
            run.font.color.rgb = DARK
            run.font.name = 'Calibri'
            p.paragraph_format.space_before = Pt(3)
            p.paragraph_format.space_after = Pt(3)
            if r_idx % 2 == 1:
                _set_cell_shading(cell, ALT_ROW_BG)

    if col_widths:
        for i, w in enumerate(col_widths):
            for row in table.rows:
                row.cells[i].width = w

    return table


def _add_footer(doc):
    p = doc.add_paragraph()
    p.paragraph_format.space_before = Pt(20)
    _add_horizontal_rule(doc, color='e0e0e0', size=2)
    footer_p = doc.add_paragraph()
    footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer_p.add_run('Generated by GoFarther AI')
    run.font.size = Pt(7)
    run.font.color.rgb = LIGHT
    run.font.name = 'Calibri'


def _money(val, sym='$'):
    try:
        return f"{sym}{float(val):,.2f}"
    except (ValueError, TypeError):
        return str(val)


# ══════════════════════════════════════════════════════════════════════════
#  INVOICE / ESTIMATE
# ══════════════════════════════════════════════════════════════════════════

def create_invoice_docx(data: dict) -> bytes:
    doc = Document()

    style = doc.styles['Normal']
    style.font.name = 'Calibri'
    style.font.size = Pt(10)
    style.font.color.rgb = DARK

    sections = doc.sections
    for section in sections:
        section.top_margin = Cm(1.5)
        section.bottom_margin = Cm(1.5)
        section.left_margin = Cm(2)
        section.right_margin = Cm(2)

    currency = data.get('currency', 'USD')
    sym = {'USD': '$', 'EUR': '€', 'GBP': '£', 'CAD': 'C$', 'AUD': 'A$'}.get(currency, '$')
    is_estimate = data.get('document_type', 'invoice').lower() in ('estimate', 'quote')
    doc_label = 'ESTIMATE' if is_estimate else 'INVOICE'

    # Title
    title_p = doc.add_paragraph()
    title_run = title_p.add_run(doc_label)
    title_run.font.size = Pt(28)
    title_run.font.color.rgb = DARK
    title_run.font.bold = True

    # Accent line
    _add_horizontal_rule(doc, color='ec4899', size=12)

    # Invoice details row
    inv_number = data.get('invoice_number', 'EST-0001' if is_estimate else 'INV-0001')
    inv_date = data.get('date', datetime.now().strftime('%Y-%m-%d'))
    due_date = data.get('due_date', '')

    details_table = doc.add_table(rows=3 if (due_date and not is_estimate) else 2, cols=2)
    details_table.columns[0].width = Inches(1.2)
    details_table.columns[1].width = Inches(2.0)

    num_label = 'ESTIMATE NO.' if is_estimate else 'INVOICE NO.'
    labels = [(num_label, inv_number), ('DATE', inv_date)]
    if due_date and not is_estimate:
        labels.append(('DUE DATE', due_date))
    elif is_estimate:
        labels.append(('VALID FOR', '30 days'))

    for i, (label, value) in enumerate(labels):
        lbl_cell = details_table.rows[i].cells[0]
        lbl_cell.text = ''
        lbl_run = lbl_cell.paragraphs[0].add_run(label)
        lbl_run.font.size = Pt(8)
        lbl_run.font.color.rgb = LIGHT
        lbl_run.font.bold = True
        lbl_run.font.name = 'Calibri'

        val_cell = details_table.rows[i].cells[1]
        val_cell.text = ''
        val_run = val_cell.paragraphs[0].add_run(value)
        val_run.font.size = Pt(10)
        val_run.font.color.rgb = ACCENT_BLUE if i == 0 else DARK
        val_run.font.bold = (i == 0)
        val_run.font.name = 'Calibri'

    doc.add_paragraph()

    # From / To
    addr_table = doc.add_table(rows=1, cols=2)
    addr_table.columns[0].width = Inches(3.2)
    addr_table.columns[1].width = Inches(3.2)

    from_data = data.get('from', {})
    to_data = data.get('to', {})

    for col_idx, (label, info) in enumerate([('FROM', from_data), ('BILL TO', to_data)]):
        cell = addr_table.rows[0].cells[col_idx]
        cell.text = ''

        lbl_p = cell.paragraphs[0]
        lbl_run = lbl_p.add_run(label)
        lbl_run.font.size = Pt(8)
        lbl_run.font.color.rgb = LIGHT
        lbl_run.font.bold = True
        lbl_run.font.name = 'Calibri'
        lbl_p.paragraph_format.space_after = Pt(4)

        company_p = cell.add_paragraph()
        company_run = company_p.add_run(info.get('company', info.get('name', '')))
        company_run.font.size = Pt(12)
        company_run.font.bold = True
        company_run.font.color.rgb = DARK
        company_run.font.name = 'Calibri'
        company_p.paragraph_format.space_after = Pt(2)

        for field in ['address', 'email', 'phone']:
            val = info.get(field, '')
            if val:
                fp = cell.add_paragraph()
                fr = fp.add_run(val)
                fr.font.size = Pt(9)
                fr.font.color.rgb = MID
                fr.font.name = 'Calibri'
                fp.paragraph_format.space_after = Pt(1)

    doc.add_paragraph()

    # Line items table
    items = data.get('items', [])
    headers = ['DESCRIPTION', 'QTY', 'RATE', 'AMOUNT']
    rows = []
    for item in items:
        desc = item.get('description', '')
        details = item.get('details', '')
        if details:
            desc += f' — {details}'
        rows.append([
            desc,
            str(item.get('qty', item.get('quantity', 1))),
            _money(item.get('rate', item.get('unit_price', item.get('price', 0))), sym),
            _money(item.get('amount', 0), sym),
        ])

    items_table = doc.add_table(rows=1 + len(rows), cols=4)
    items_table.alignment = WD_TABLE_ALIGNMENT.CENTER

    col_widths = [Inches(3.2), Inches(0.8), Inches(1.2), Inches(1.2)]
    alignments = [WD_ALIGN_PARAGRAPH.LEFT, WD_ALIGN_PARAGRAPH.CENTER, WD_ALIGN_PARAGRAPH.RIGHT, WD_ALIGN_PARAGRAPH.RIGHT]

    for i, h in enumerate(headers):
        cell = items_table.rows[0].cells[i]
        cell.text = ''
        cell.width = col_widths[i]
        p = cell.paragraphs[0]
        p.alignment = alignments[i]
        run = p.add_run(h)
        run.font.size = Pt(8)
        run.font.color.rgb = WHITE
        run.font.bold = True
        run.font.name = 'Calibri'
        p.paragraph_format.space_before = Pt(6)
        p.paragraph_format.space_after = Pt(6)
        _set_cell_shading(cell, TABLE_HEADER_BG)

    for r_idx, row_data in enumerate(rows):
        for c_idx, val in enumerate(row_data):
            cell = items_table.rows[r_idx + 1].cells[c_idx]
            cell.text = ''
            cell.width = col_widths[c_idx]
            p = cell.paragraphs[0]
            p.alignment = alignments[c_idx]
            run = p.add_run(str(val))
            run.font.size = Pt(9)
            run.font.color.rgb = DARK
            run.font.name = 'Calibri'
            p.paragraph_format.space_before = Pt(4)
            p.paragraph_format.space_after = Pt(4)
            if r_idx % 2 == 1:
                _set_cell_shading(cell, ALT_ROW_BG)

    doc.add_paragraph()

    # Totals
    subtotal = data.get('subtotal', 0)
    tax_rate = data.get('tax_rate', 0)
    tax_amount = data.get('tax_amount', 0)
    discount = data.get('discount', 0)
    total = data.get('total', 0)

    totals_table = doc.add_table(rows=0, cols=2)
    totals_table.alignment = WD_TABLE_ALIGNMENT.RIGHT
    totals_table.columns[0].width = Inches(1.5)
    totals_table.columns[1].width = Inches(1.5)

    total_lines = [('Subtotal', _money(subtotal, sym))]
    if discount:
        total_lines.append(('Discount', f'-{_money(discount, sym)}'))
    if tax_rate:
        total_lines.append((f'Tax ({tax_rate}%)', _money(tax_amount, sym)))
    total_lines.append(('TOTAL', _money(total, sym)))

    for label, value in total_lines:
        row = totals_table.add_row()
        is_total = label == 'TOTAL'

        lbl_cell = row.cells[0]
        lbl_cell.text = ''
        lbl_p = lbl_cell.paragraphs[0]
        lbl_p.alignment = WD_ALIGN_PARAGRAPH.RIGHT
        lbl_run = lbl_p.add_run(label)
        lbl_run.font.size = Pt(11) if is_total else Pt(9)
        lbl_run.font.bold = is_total
        lbl_run.font.color.rgb = DARK
        lbl_run.font.name = 'Calibri'

        val_cell = row.cells[1]
        val_cell.text = ''
        val_p = val_cell.paragraphs[0]
        val_p.alignment = WD_ALIGN_PARAGRAPH.RIGHT
        val_run = val_p.add_run(value)
        val_run.font.size = Pt(14) if is_total else Pt(9)
        val_run.font.bold = is_total
        val_run.font.color.rgb = ACCENT_BLUE if is_total else DARK
        val_run.font.name = 'Calibri'

        if is_total:
            _set_cell_shading(lbl_cell, ALT_ROW_BG)
            _set_cell_shading(val_cell, ALT_ROW_BG)

    # Notes
    notes = data.get('notes', '')
    payment = data.get('payment_methods', data.get('payment_method', ''))
    if notes or payment:
        doc.add_paragraph()
        _add_horizontal_rule(doc)
        if notes:
            notes_p = doc.add_paragraph()
            notes_lbl = notes_p.add_run('Notes: ')
            notes_lbl.font.size = Pt(9)
            notes_lbl.font.bold = True
            notes_lbl.font.color.rgb = MID
            notes_lbl.font.name = 'Calibri'
            notes_val = notes_p.add_run(notes)
            notes_val.font.size = Pt(9)
            notes_val.font.color.rgb = MID
            notes_val.font.name = 'Calibri'
        if payment:
            pay_p = doc.add_paragraph()
            pay_lbl = pay_p.add_run('Payment Methods: ')
            pay_lbl.font.size = Pt(9)
            pay_lbl.font.bold = True
            pay_lbl.font.color.rgb = MID
            pay_lbl.font.name = 'Calibri'
            pay_val = pay_p.add_run(payment)
            pay_val.font.size = Pt(9)
            pay_val.font.color.rgb = MID
            pay_val.font.name = 'Calibri'

    _add_footer(doc)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


# ══════════════════════════════════════════════════════════════════════════
#  ROUTING
# ══════════════════════════════════════════════════════════════════════════

def render_structured_docx(doc_type: str, data: dict) -> bytes:
    renderers = {
        'invoice': create_invoice_docx,
    }
    renderer = renderers.get(doc_type)
    if not renderer:
        raise ValueError(f"No DOCX template for: {doc_type}")
    return renderer(data)
