"""
Professional PDF Templates for GoFarther AI.
Uses reportlab for high-quality PDF generation with custom styling.
"""

import io
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor, black, white
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, HRFlowable, Frame, PageTemplate
)
from reportlab.pdfgen import canvas


# Brand colors
PRIMARY = HexColor('#ec4899')
DARK = HexColor('#1a1a1a')
MID = HexColor('#666666')
LIGHT = HexColor('#f5f5f5')
BORDER = HexColor('#e0e0e0')
WHITE = white


def _create_styles():
    """Create professional paragraph styles."""
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle(
        'DocTitle', parent=styles['Title'],
        fontSize=28, leading=34, textColor=DARK,
        spaceAfter=6, fontName='Helvetica-Bold',
    ))
    styles.add(ParagraphStyle(
        'DocSubtitle', parent=styles['Normal'],
        fontSize=12, leading=16, textColor=MID,
        spaceAfter=24, fontName='Helvetica',
    ))
    styles.add(ParagraphStyle(
        'H1', parent=styles['Heading1'],
        fontSize=20, leading=26, textColor=DARK,
        spaceBefore=20, spaceAfter=10,
        fontName='Helvetica-Bold',
        borderColor=PRIMARY, borderWidth=0, borderPadding=0,
    ))
    styles.add(ParagraphStyle(
        'H2', parent=styles['Heading2'],
        fontSize=16, leading=22, textColor=DARK,
        spaceBefore=16, spaceAfter=8,
        fontName='Helvetica-Bold',
    ))
    styles.add(ParagraphStyle(
        'H3', parent=styles['Heading3'],
        fontSize=13, leading=18, textColor=DARK,
        spaceBefore=12, spaceAfter=6,
        fontName='Helvetica-Bold',
    ))
    styles.add(ParagraphStyle(
        'Body', parent=styles['Normal'],
        fontSize=11, leading=16, textColor=DARK,
        spaceAfter=8, fontName='Helvetica',
    ))
    styles.add(ParagraphStyle(
        'BulletItem', parent=styles['Normal'],
        fontSize=11, leading=16, textColor=DARK,
        spaceAfter=4, fontName='Helvetica',
        leftIndent=20, bulletIndent=8,
    ))
    styles.add(ParagraphStyle(
        'Footer', parent=styles['Normal'],
        fontSize=8, leading=10, textColor=MID,
        fontName='Helvetica', alignment=TA_CENTER,
    ))

    return styles


class HeaderFooter:
    """Draws header and footer on every page."""

    def __init__(self, title: str = "GoFarther AI"):
        self.title = title

    def __call__(self, canvas_obj, doc):
        canvas_obj.saveState()
        width, height = letter

        # Header line
        canvas_obj.setStrokeColor(PRIMARY)
        canvas_obj.setLineWidth(2)
        canvas_obj.line(0.75 * inch, height - 0.6 * inch, width - 0.75 * inch, height - 0.6 * inch)

        # Header text
        canvas_obj.setFont('Helvetica', 8)
        canvas_obj.setFillColor(MID)
        canvas_obj.drawString(0.75 * inch, height - 0.5 * inch, self.title)
        canvas_obj.drawRightString(width - 0.75 * inch, height - 0.5 * inch, datetime.now().strftime('%B %d, %Y'))

        # Footer
        canvas_obj.setStrokeColor(BORDER)
        canvas_obj.setLineWidth(0.5)
        canvas_obj.line(0.75 * inch, 0.6 * inch, width - 0.75 * inch, 0.6 * inch)

        canvas_obj.setFont('Helvetica', 8)
        canvas_obj.setFillColor(MID)
        canvas_obj.drawString(0.75 * inch, 0.4 * inch, "Generated by GoFarther AI")
        canvas_obj.drawRightString(width - 0.75 * inch, 0.4 * inch, f"Page {doc.page}")

        canvas_obj.restoreState()


def create_professional_pdf(content: str, title: str = None) -> bytes:
    """
    Create a professionally styled PDF from markdown-like content.

    Supports:
    - # Heading 1, ## Heading 2, ### Heading 3
    - - Bullet points
    - 1. Numbered items
    - Regular paragraphs
    - --- Horizontal rules
    - **bold** text
    """
    buf = io.BytesIO()
    styles = _create_styles()

    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
        topMargin=0.85 * inch,
        bottomMargin=0.85 * inch,
    )

    story = []

    # Auto-detect title from first heading
    lines = content.split('\n')
    doc_title = title

    if not doc_title:
        for line in lines:
            line = line.strip()
            if line.startswith('# '):
                doc_title = line[2:].strip()
                break
        if not doc_title:
            doc_title = "Document"

    # Title section
    story.append(Spacer(1, 20))
    story.append(Paragraph(doc_title, styles['DocTitle']))
    story.append(Paragraph(f"Generated on {datetime.now().strftime('%B %d, %Y')}", styles['DocSubtitle']))

    # Pink accent bar under title
    story.append(HRFlowable(width="30%", thickness=3, color=PRIMARY, spaceAfter=20))

    # Parse content
    skip_first_heading = True
    for line in lines:
        line = line.strip()

        if not line:
            story.append(Spacer(1, 6))
            continue

        # Horizontal rule
        if line.startswith('---'):
            story.append(Spacer(1, 8))
            story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER, spaceAfter=8))
            continue

        # Headings
        if line.startswith('# ') and not line.startswith('## '):
            if skip_first_heading:
                skip_first_heading = False
                continue  # Already used as title
            text = _format_inline(line[2:].strip())
            story.append(Spacer(1, 4))
            story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER, spaceAfter=4))
            story.append(Paragraph(text, styles['H1']))
            continue

        if line.startswith('## '):
            text = _format_inline(line[3:].strip())
            story.append(Paragraph(text, styles['H2']))
            continue

        if line.startswith('### '):
            text = _format_inline(line[4:].strip())
            story.append(Paragraph(text, styles['H3']))
            continue

        # Bullet points
        if line.startswith('- ') or line.startswith('• ') or line.startswith('* '):
            text = _format_inline(line[2:].strip())
            story.append(Paragraph(f"•  {text}", styles['BulletItem']))
            continue

        # Numbered items
        import re
        num_match = re.match(r'^(\d+)\.\s+(.+)$', line)
        if num_match:
            text = _format_inline(num_match.group(2))
            story.append(Paragraph(f"{num_match.group(1)}.  {text}", styles['BulletItem']))
            continue

        # Regular paragraph
        text = _format_inline(line)
        story.append(Paragraph(text, styles['Body']))

    # Build with header/footer
    hf = HeaderFooter(doc_title)
    doc.build(story, onFirstPage=hf, onLaterPages=hf)

    return buf.getvalue()


def _format_inline(text: str) -> str:
    """Convert markdown inline formatting to reportlab XML tags."""
    import re

    # Bold **text**
    text = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', text)

    # Italic *text*
    text = re.sub(r'\*(.+?)\*', r'<i>\1</i>', text)

    # Inline code `text`
    text = re.sub(r'`(.+?)`', r'<font face="Courier" size="10" color="#c7254e">\1</font>', text)

    # Escape any remaining XML-unsafe characters
    # (but don't escape our intentional tags)

    return text
