export interface Connector {
  id: string;
  name: string;
  logo: string; // logo image URL
  color: string; // brand color (used for the fallback monogram)
  desc: string;
  // How the user connects. Omitted = 'oauth' (one-click Composio-managed OAuth).
  // 'apikey' = paste a key; 'keyless' = no auth needed (public API).
  auth?: 'oauth' | 'apikey' | 'keyless';
}

// Brand logos: simple-icons CDN where available, Google's favicon service for
// the few brands not in open icon sets, Composio's logo CDN for the long tail.
const si = (slug: string) => `https://cdn.simpleicons.org/${slug}`;
const fav = (domain: string) => `https://www.google.com/s2/favicons?sz=128&domain=${domain}`;
const cl = (slug: string) => `https://logos.composio.dev/api/${slug}`;

// All connectors run through Composio (OAuth + MCP). The endpoint slug is
// historical (`gmail-oauth`) but it connects any app via ?app=<id>.
export const CONNECT_API = 'https://lkpfeqrelvziltfwpuxi.supabase.co/functions/v1/gmail-oauth';

export const CONNECTORS: Connector[] = [
  { id: 'gdrive', name: 'Google Drive', logo: si('googledrive'), color: '#1FA463', desc: 'Search and read your files' },
  { id: 'gmail', name: 'Gmail', logo: si('gmail'), color: '#EA4335', desc: 'Read, search and draft emails' },
  { id: 'gcal', name: 'Google Calendar', logo: si('googlecalendar'), color: '#4285F4', desc: 'Check and create events' },
  // Plaid is NOT a Composio connector — it links a bank via the `plaid` Edge
  // Function (hosted Link). ConnectorsGraph special-cases this id for connect/
  // status/disconnect; the chat & workflow `apps` list stays Composio-only.
  { id: 'plaid', name: 'Plaid', logo: si('plaid'), color: '#111111', desc: 'Link your bank — balances & transactions' },
  { id: 'canva', name: 'Canva', logo: fav('canva.com'), color: '#00C4CC', desc: 'Designs and brand assets' },
  { id: 'figma', name: 'Figma', logo: si('figma'), color: '#F24E1E', desc: 'Design files and prototypes' },
  { id: 'notion', name: 'Notion', logo: si('notion'), color: '#111111', desc: 'Search and edit your workspace' },
  { id: 'atlassian', name: 'Atlassian Jira', logo: si('jira'), color: '#0052CC', desc: 'Search, read & create Jira issues' },
  { id: 'm365', name: 'Microsoft Outlook', logo: fav('outlook.com'), color: '#0078D4', desc: 'Outlook mail & calendar' },
  { id: 'slack', name: 'Slack', logo: fav('slack.com'), color: '#4A154B', desc: 'Read and send messages' },
  { id: 'hubspot', name: 'HubSpot', logo: si('hubspot'), color: '#FF7A59', desc: 'Contacts, deals & CRM' },
  { id: 'googlesheets', name: 'Google Sheets', logo: si('googlesheets'), color: '#0F9D58', desc: 'Read & edit spreadsheets' },
  { id: 'googledocs', name: 'Google Docs', logo: si('googledocs'), color: '#4285F4', desc: 'Read & write documents' },
  { id: 'excel', name: 'Microsoft Excel', logo: fav('office.com'), color: '#217346', desc: 'Spreadsheets & workbooks' },
  { id: 'one_drive', name: 'OneDrive', logo: fav('onedrive.com'), color: '#0078D4', desc: 'Find & manage your files' },
  { id: 'dropbox', name: 'Dropbox', logo: si('dropbox'), color: '#0061FF', desc: 'Find & share files' },
  { id: 'box', name: 'Box', logo: si('box'), color: '#0061D5', desc: 'Cloud files & folders' },
  { id: 'onenote', name: 'OneNote', logo: fav('onenote.com'), color: '#7719AA', desc: 'Notes & notebooks' },
  { id: 'airtable', name: 'Airtable', logo: si('airtable'), color: '#18BFFF', desc: 'Bases, tables & records' },
  { id: 'todoist', name: 'Todoist', logo: si('todoist'), color: '#E44332', desc: 'Tasks & to-dos' },
  { id: 'googletasks', name: 'Google Tasks', logo: si('googletasks'), color: '#4285F4', desc: 'Your Google to-dos' },
  { id: 'asana', name: 'Asana', logo: si('asana'), color: '#F06A6A', desc: 'Tasks & projects' },
  { id: 'trello', name: 'Trello', logo: si('trello'), color: '#0052CC', desc: 'Boards & cards' },
  { id: 'clickup', name: 'ClickUp', logo: si('clickup'), color: '#7B68EE', desc: 'Tasks & docs' },
  { id: 'monday', name: 'monday.com', logo: fav('monday.com'), color: '#FF3D57', desc: 'Work boards & items' },
  { id: 'miro', name: 'Miro', logo: si('miro'), color: '#FFD02F', desc: 'Boards & diagrams' },
  { id: 'calendly', name: 'Calendly', logo: si('calendly'), color: '#006BFF', desc: 'Scheduling & bookings' },
  { id: 'zoom', name: 'Zoom', logo: si('zoom'), color: '#0B5CFF', desc: 'Meetings & recordings' },
  { id: 'googlemeet', name: 'Google Meet', logo: si('googlemeet'), color: '#00897B', desc: 'Video meetings' },
  { id: 'microsoft_teams', name: 'Microsoft Teams', logo: fav('teams.microsoft.com'), color: '#6264A7', desc: 'Chats & channels' },
  { id: 'webex', name: 'Webex', logo: si('webex'), color: '#005073', desc: 'Meetings & messaging' },
  { id: 'telegram', name: 'Telegram', logo: si('telegram'), color: '#26A5E4', desc: 'Send & read messages' },
  { id: 'discord', name: 'Discord', logo: si('discord'), color: '#5865F2', desc: 'Servers & messages' },
  { id: 'linkedin', name: 'LinkedIn', logo: fav('linkedin.com'), color: '#0A66C2', desc: 'Posts & profile' },
  { id: 'reddit', name: 'Reddit', logo: si('reddit'), color: '#FF4500', desc: 'Browse & post' },
  { id: 'youtube', name: 'YouTube', logo: si('youtube'), color: '#FF0000', desc: 'Videos & channels' },
  { id: 'instagram', name: 'Instagram', logo: si('instagram'), color: '#E4405F', desc: 'Posts & media' },
  { id: 'twitter', name: 'X (Twitter)', logo: si('x'), color: '#000000', desc: 'Post & read tweets' },
  { id: 'spotify', name: 'Spotify', logo: si('spotify'), color: '#1DB954', desc: 'Music & playlists' },
  { id: 'salesforce', name: 'Salesforce', logo: fav('salesforce.com'), color: '#00A1E0', desc: 'CRM records & leads' },
  { id: 'pipedrive', name: 'Pipedrive', logo: fav('pipedrive.com'), color: '#017737', desc: 'Deals & contacts' },
  { id: 'zoho', name: 'Zoho', logo: si('zoho'), color: '#E42527', desc: 'CRM & business apps' },
  { id: 'zendesk', name: 'Zendesk', logo: si('zendesk'), color: '#03363D', desc: 'Support tickets' },
  { id: 'intercom', name: 'Intercom', logo: si('intercom'), color: '#1F8DED', desc: 'Conversations & contacts' },
  { id: 'freshdesk', name: 'Freshdesk', logo: fav('freshdesk.com'), color: '#06C167', desc: 'Support tickets' },
  { id: 'shopify', name: 'Shopify', logo: si('shopify'), color: '#7AB55C', desc: 'Orders, products & customers' },
  { id: 'stripe', name: 'Stripe', logo: si('stripe'), color: '#635BFF', desc: 'Payments & customers' },
  { id: 'square', name: 'Square', logo: si('square'), color: '#3E4348', desc: 'Payments & catalog' },
  { id: 'quickbooks', name: 'QuickBooks', logo: si('quickbooks'), color: '#2CA01C', desc: 'Invoices & accounting' },
  { id: 'xero', name: 'Xero', logo: si('xero'), color: '#13B5EA', desc: 'Accounting & invoices' },
  { id: 'typeform', name: 'Typeform', logo: si('typeform'), color: '#262627', desc: 'Forms & responses' },
  { id: 'jotform', name: 'Jotform', logo: fav('jotform.com'), color: '#0099FF', desc: 'Forms & submissions' },
  { id: 'mailchimp', name: 'Mailchimp', logo: si('mailchimp'), color: '#FFE01B', desc: 'Campaigns & audiences' },
  { id: 'sendgrid', name: 'SendGrid', logo: fav('sendgrid.com'), color: '#1A82E2', desc: 'Send transactional email' },
  { id: 'klaviyo', name: 'Klaviyo', logo: fav('klaviyo.com'), color: '#000000', desc: 'Email & SMS marketing' },
  { id: 'github', name: "GitHub", logo: si('github'), color: '#181717', desc: "Developer tools" },
  { id: 'googlesuper', name: "Google Super", logo: fav('googlesuper'), color: '#6B7280', desc: "Document & File Management" },
  { id: 'pagerduty', name: "PagerDuty", logo: si('pagerduty'), color: '#06AC38', desc: "Server Monitoring" },
  { id: 'zoho_books', name: "Zoho Books", logo: fav('zoho_books'), color: '#6B7280', desc: "Accounting & invoices" },
  { id: 'crowdin', name: "Crowdin", logo: si('crowdin'), color: '#2E3340', desc: "Developer tools" },
  { id: 'sentry', name: "Sentry", logo: si('sentry'), color: '#362D59', desc: "Developer tools" },
  { id: 'dialpad', name: "Dialpad", logo: fav('dialpad'), color: '#6B7280', desc: "Messaging" },
  { id: 'cal', name: "Cal", logo: fav('cal'), color: '#6B7280', desc: "Scheduling" },
  { id: 'discordbot', name: "Discord Bot", logo: fav('discordbot'), color: '#6B7280', desc: "Team Chat" },
  { id: 'wrike', name: "Wrike", logo: fav('wrike'), color: '#6B7280', desc: "Projects & tasks" },
  { id: 'basecamp', name: "Basecamp", logo: si('basecamp'), color: '#1D2D35', desc: "Projects & tasks" },
  { id: 'zoho_invoice', name: "Zoho Invoice", logo: fav('zoho_invoice'), color: '#6B7280', desc: "Proposal & Invoice Management" },
  { id: 'hugging_face', name: "Hugging Face", logo: si('huggingface'), color: '#FFD21E', desc: "Artificial Intelligence" },
  { id: 'stack_exchange', name: "Stack Exchange", logo: si('stackexchange'), color: '#1E5397', desc: "Developer tools" },
  { id: 'supabase', name: "Supabase", logo: si('supabase'), color: '#3FCF8E', desc: "Developer tools" },
  { id: 'capsule_crm', name: "Capsule CRM", logo: fav('capsule_crm'), color: '#6B7280', desc: "CRM & sales" },
  { id: 'contentful', name: "Contentful", logo: si('contentful'), color: '#2478CC', desc: "Developer tools" },
  { id: 'bitbucket', name: "Bitbucket", logo: si('bitbucket'), color: '#0052CC', desc: "Developer tools" },
  { id: 'productboard', name: "Productboard", logo: fav('productboard'), color: '#6B7280', desc: "Product Management" },
  { id: 'attio', name: "Attio", logo: fav('attio'), color: '#6B7280', desc: "CRM & sales" },
  { id: 'share_point', name: "SharePoint", logo: fav('share_point'), color: '#6B7280', desc: "Docs & files" },
  { id: 'shippo', name: "Shippo", logo: fav('shippo'), color: '#6B7280', desc: "Commerce" },
  { id: 'eventbrite', name: "Eventbrite", logo: si('eventbrite'), color: '#6B7280', desc: "Event Management" },
  { id: 'slackbot', name: "Slackbot", logo: fav('slackbot'), color: '#6B7280', desc: "Team Chat" },
  { id: 'reddit_ads', name: "Reddit Ads", logo: fav('reddit_ads'), color: '#6B7280', desc: "Marketing" },
  { id: 'freeagent', name: "Freeagent", logo: fav('freeagent'), color: '#6B7280', desc: "Accounting & invoices" },
  { id: 'google_analytics', name: "Google Analytics", logo: si('googleanalytics'), color: '#E37400', desc: "Analytics & data" },
  { id: 'googlebigquery', name: "Google BigQuery", logo: si('googlebigquery'), color: '#669DF6', desc: "Databases" },
  { id: 'confluence', name: "Confluence", logo: si('confluence'), color: '#172B4D', desc: "Team Collaboration" },
  { id: 'google_classroom', name: "Google Classroom", logo: si('googleclassroom'), color: '#0F9D58', desc: "Education" },
  { id: 'gitlab', name: "GitLab", logo: si('gitlab'), color: '#FC6D26', desc: "Developer tools" },
  { id: 'zoho_inventory', name: "Zoho Inventory", logo: fav('zoho_inventory'), color: '#6B7280', desc: "Accounting & invoices" },
  { id: 'gong', name: "Gong", logo: fav('gong'), color: '#6B7280', desc: "Analytics & data" },
  { id: 'harvest', name: "Harvest", logo: fav('harvest'), color: '#6B7280', desc: "Time Tracking Software" },
  { id: 'zoho_bigin', name: "Zoho Bigin", logo: fav('zoho_bigin'), color: '#6B7280', desc: "CRM & sales" },
  { id: 'digital_ocean', name: "DigitalOcean", logo: si('digitalocean'), color: '#0080FF', desc: "Developer tools" },
  { id: 'omnisend', name: "Omnisend", logo: fav('omnisend'), color: '#6B7280', desc: "Marketing automation" },
  { id: 'kit', name: "Kit", logo: si('kit'), color: '#000000', desc: "Marketing automation" },
  { id: 'timely', name: "Timely", logo: fav('timely'), color: '#6B7280', desc: "Time Tracking Software" },
  { id: 'facebook', name: "Facebook", logo: si('facebook'), color: '#0866FF', desc: "Social Media Accounts" },
  { id: 'roam', name: "Roam", logo: fav('roam'), color: '#6B7280', desc: "Messaging" },
  { id: 'strava', name: "Strava", logo: si('strava'), color: '#FC4C02', desc: "Fitness" },
  { id: 'gorgias', name: "Gorgias", logo: fav('gorgias'), color: '#6B7280', desc: "CRM & sales" },
  { id: 'linear', name: "Linear", logo: si('linear'), color: '#5E6AD2', desc: "Projects & tasks" },
  { id: 'apaleo', name: "Apaleo", logo: fav('apaleo'), color: '#6B7280', desc: "Scheduling" },
  { id: 'servicem8', name: "Servicem8", logo: fav('servicem8'), color: '#6B7280', desc: "Scheduling" },
  { id: 'ynab', name: "YNAB", logo: fav('ynab'), color: '#6B7280', desc: "Accounting & invoices" },
  { id: 'splitwise', name: "Splitwise", logo: fav('splitwise'), color: '#6B7280', desc: "Accounting & invoices" },
  { id: 'toneden', name: "Toneden", logo: fav('toneden'), color: '#6B7280', desc: "Social Media Marketing" },
  { id: 'zeplin', name: "Zeplin", logo: fav('zeplin'), color: '#6B7280', desc: "Images & Design" },
  { id: 'zoho_desk', name: "Zoho Desk", logo: fav('zoho_desk'), color: '#6B7280', desc: "CRM & sales" },
  { id: 'prisma', name: "Prisma", logo: si('prisma'), color: '#2D3748', desc: "Databases" },
  { id: 'mural', name: "Mural", logo: si('mural'), color: '#FF4B4B', desc: "Team Collaboration" },
  { id: 'moneybird', name: "Moneybird", logo: fav('moneybird'), color: '#6B7280', desc: "Accounting & invoices" },
  { id: 'yandex', name: "Yandex", logo: si('yandex'), color: '#6B7280', desc: "Email" },
  { id: 'google_maps', name: "Google Maps", logo: si('googlemaps'), color: '#4285F4', desc: "Developer tools" },
  { id: 'dart', name: "Dart", logo: si('dart'), color: '#0175C2', desc: "Projects & tasks" },
  { id: 'whatsapp', name: "WhatsApp", logo: si('whatsapp'), color: '#25D366', desc: "Connect this app" },
  { id: 'dub', name: "Dub", logo: fav('dub'), color: '#6B7280', desc: "Url Shortener" },
  { id: 'wakatime', name: "WakaTime", logo: si('wakatime'), color: '#000000', desc: "Time Tracking Software" },
  { id: 'dynamics365', name: "Dynamics 365", logo: si('dynamics365'), color: '#6B7280', desc: "CRM & sales" },
  { id: 'ticketmaster', name: "Ticketmaster", logo: si('ticketmaster'), color: '#026CDF', desc: "Event Management" },
  { id: 'pushbullet', name: "Pushbullet", logo: si('pushbullet'), color: '#4AB367', desc: "Notifications" },
  { id: 'zoho_mail', name: "Zoho Mail", logo: fav('zoho_mail'), color: '#6B7280', desc: "Email" },
  { id: 'boldsign', name: "Boldsign", logo: fav('boldsign'), color: '#6B7280', desc: "Connect this app" },
  { id: 'googlephotos', name: "Google Photos", logo: si('googlephotos'), color: '#4285F4', desc: "Connect this app" },
  { id: 'ticktick', name: "Ticktick", logo: si('ticktick'), color: '#4772FA', desc: "Productivity" },
  { id: 'exist', name: "Exist", logo: fav('exist'), color: '#6B7280', desc: "Analytics & data" },
  { id: 'freshbooks', name: "FreshBooks", logo: fav('freshbooks'), color: '#6B7280', desc: "Accounting & invoices" },
  { id: 'google_search_console', name: "Google Search Console", logo: si('googlesearchconsole'), color: '#458CF5', desc: "Analytics & data" },
  { id: 'googleads', name: "Google Ads", logo: si('googleads'), color: '#4285F4', desc: "Ads & Conversion" },
  { id: 'fathom', name: "Fathom", logo: si('fathom'), color: '#9187FF', desc: "Ai Meeting Assistants" },
  { id: 'gumroad', name: "Gumroad", logo: si('gumroad'), color: '#FF90E8', desc: "Commerce" },
  { id: 'googleslides', name: "Google Slides", logo: si('googleslides'), color: '#FBBC04', desc: "Docs & files" },
  { id: 'linkhut', name: "Linkhut", logo: fav('linkhut'), color: '#6B7280', desc: "Bookmark Managers" },
  { id: 'blackbaud', name: "Blackbaud", logo: fav('blackbaud'), color: '#6B7280', desc: "Connect this app" },
  { id: 'hackernews', name: "Hacker News", logo: cl('hackernews'), color: '#6B7280', desc: "News & Lifestyle", auth: 'keyless' },
  { id: 'weathermap', name: "OpenWeatherMap", logo: cl('weathermap'), color: '#6B7280', desc: "Developer tools", auth: 'keyless' },
  { id: 'gemini', name: "Gemini", logo: cl('gemini'), color: '#6B7280', desc: "AI", auth: 'keyless' },
  { id: 'instacart', name: "Instacart", logo: si('instacart'), color: '#43B02A', desc: "Commerce", auth: 'keyless' },
  { id: 'seat_geek', name: "Seat Geek", logo: si('seatgeek'), color: '#FF5B49', desc: "Event Management", auth: 'keyless' },
  { id: 'yelp', name: "Yelp", logo: si('yelp'), color: '#FF1A1A', desc: "Reviews", auth: 'keyless' },
  { id: 'datarobot', name: "DataRobot", logo: cl('datarobot'), color: '#6B7280', desc: "AI", auth: 'apikey' },
  { id: 'canvas', name: "Canvas", logo: si('canvas'), color: '#E72429', desc: "Online Courses", auth: 'apikey' },
  { id: 'posthog', name: "PostHog", logo: si('posthog'), color: '#000000', desc: "Analytics", auth: 'apikey' },
  { id: 'databricks', name: "Databricks", logo: si('databricks'), color: '#FF3621', desc: "Developer tools", auth: 'apikey' },
  { id: 'dataforseo', name: "Dataforseo", logo: cl('dataforseo'), color: '#6B7280', desc: "Developer tools", auth: 'apikey' },
  { id: 'active_campaign', name: "ActiveCampaign", logo: cl('active_campaign'), color: '#6B7280', desc: "Marketing", auth: 'apikey' },
  { id: 'benchmark_email', name: "Benchmark Email", logo: cl('benchmark_email'), color: '#6B7280', desc: "Email", auth: 'apikey' },
  { id: 'chatbotkit', name: "Chatbotkit", logo: cl('chatbotkit'), color: '#6B7280', desc: "Ai Chatbots", auth: 'apikey' },
  { id: 'safetyculture', name: "SafetyCulture", logo: cl('safetyculture'), color: '#6B7280', desc: "Forms", auth: 'apikey' },
  { id: 'launch_darkly', name: "LaunchDarkly", logo: cl('launch_darkly'), color: '#6B7280', desc: "Developer tools", auth: 'apikey' },
  { id: 'moco', name: "Moco", logo: cl('moco'), color: '#6B7280', desc: "Projects", auth: 'apikey' },
  { id: 'metabase', name: "Metabase", logo: si('metabase'), color: '#509EE3', desc: "Business Intelligence", auth: 'apikey' },
  { id: 'centralstationcrm', name: "CentralStationCRM", logo: cl('centralstationcrm'), color: '#6B7280', desc: "CRM & sales", auth: 'apikey' },
  { id: 'gleap', name: "Gleap", logo: cl('gleap'), color: '#6B7280', desc: "Support", auth: 'apikey' },
  { id: 'maxio', name: "Maxio", logo: cl('maxio'), color: '#6B7280', desc: "Commerce", auth: 'apikey' },
  { id: 'servicenow', name: "ServiceNow", logo: cl('servicenow'), color: '#6B7280', desc: "Connect with an API key", auth: 'apikey' },
  { id: 'dnsfilter', name: "Dnsfilter", logo: cl('dnsfilter'), color: '#6B7280', desc: "Security & Identity Tools", auth: 'apikey' },
  { id: 'turbot_pipes', name: "Turbot Pipes", logo: cl('turbot_pipes'), color: '#6B7280', desc: "Developer tools", auth: 'apikey' },
  { id: 'clicksend', name: "ClickSend", logo: cl('clicksend'), color: '#6B7280', desc: "Phone & Sms", auth: 'apikey' },
  { id: 'active_trail', name: "ActiveTrail", logo: cl('active_trail'), color: '#6B7280', desc: "Email", auth: 'apikey' },
  { id: 'new_relic', name: "New Relic", logo: si('newrelic'), color: '#1CE783', desc: "Server Monitoring", auth: 'apikey' },
  { id: 'elevenlabs', name: "ElevenLabs", logo: si('elevenlabs'), color: '#000000', desc: "AI", auth: 'apikey' },
  { id: 'borneo', name: "Borneo", logo: cl('borneo'), color: '#6B7280', desc: "Security & Identity Tools", auth: 'apikey' },
  { id: 'cloudcart', name: "Cloudcart", logo: cl('cloudcart'), color: '#6B7280', desc: "Commerce", auth: 'apikey' },
  { id: 'gigasheet', name: "Gigasheet", logo: cl('gigasheet'), color: '#6B7280', desc: "Spreadsheets", auth: 'apikey' },
  { id: 'repairshopr', name: "RepairShopr", logo: cl('repairshopr'), color: '#6B7280', desc: "CRM & sales", auth: 'apikey' },
  { id: 'griptape', name: "Griptape", logo: cl('griptape'), color: '#6B7280', desc: "AI", auth: 'apikey' },
  { id: 'bookingmood', name: "Bookingmood", logo: cl('bookingmood'), color: '#6B7280', desc: "Scheduling & Booking", auth: 'apikey' },
  { id: 'simla_com', name: "Simla.com", logo: cl('simla_com'), color: '#6B7280', desc: "CRM & sales", auth: 'apikey' },
  { id: 'wix', name: "Wix", logo: si('wix'), color: '#0C6EFC', desc: "Website Builders", auth: 'apikey' },
  { id: 'shortcut', name: "Shortcut", logo: si('shortcut'), color: '#58B1E4', desc: "Projects", auth: 'apikey' },
  { id: 'nasa', name: "Nasa", logo: si('nasa'), color: '#E03C31', desc: "Developer tools", auth: 'apikey' },
  { id: 'vercel', name: "Vercel", logo: si('vercel'), color: '#000000', desc: "Developer tools", auth: 'apikey' },
  { id: 'rentman', name: "Rentman", logo: cl('rentman'), color: '#6B7280', desc: "Productivity", auth: 'apikey' },
  { id: 'tave', name: "Tave", logo: cl('tave'), color: '#6B7280', desc: "CRM & sales", auth: 'apikey' },
  { id: 'api_ninjas', name: "API Ninjas", logo: cl('api_ninjas'), color: '#6B7280', desc: "Developer tools", auth: 'apikey' },
  { id: 'algolia', name: "Algolia", logo: si('algolia'), color: '#003DFF', desc: "Developer tools", auth: 'apikey' },
  { id: 'bunnycdn', name: "BunnyCDN", logo: cl('bunnycdn'), color: '#6B7280', desc: "Developer tools", auth: 'apikey' },
  { id: 'openai', name: "OpenAI", logo: si('openai'), color: '#6B7280', desc: "AI", auth: 'apikey' },
  { id: 'postman', name: "Postman", logo: si('postman'), color: '#FF6C37', desc: "Developer tools", auth: 'apikey' },
  { id: 'ashby', name: "Ashby", logo: cl('ashby'), color: '#6B7280', desc: "Hr Talent & Recruitment", auth: 'apikey' },
  { id: 'elevenreader', name: "Elevenreader", logo: cl('elevenreader'), color: '#6B7280', desc: "AI", auth: 'apikey' },
  { id: 'fireberry', name: "Fireberry", logo: cl('fireberry'), color: '#6B7280', desc: "CRM & sales", auth: 'apikey' },
  { id: 'hub_planner', name: "Hub Planner", logo: cl('hub_planner'), color: '#6B7280', desc: "Productivity", auth: 'apikey' },
  { id: 'better_stack', name: "Better Stack", logo: si('betterstack'), color: '#000000', desc: "Server Monitoring", auth: 'apikey' },
];

export const byId = (id: string) => CONNECTORS.find((c) => c.id === id);
